### ISSUE TITLE
Ajouter l'émotion dans Souveraineté et Lien 

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/La_demarche_gouvernance_cellulaire#100]
Proposition de correction légère pour cette diapo en rose

![image](https://user-images.githubusercontent.com/38285180/233657103-7042eabd-24d5-4dd5-8a6a-f96c47538fe5.png)

**Comment by Maylis-De-Almeida** [comment]
Coucou! Contente d'être ici! 
Une question: en quoi "l'expression d'une tension a postériori" rejoint la phase dont on parle ici, qui se passe "avant" la retenue d'option? Ca me donne l'impression qu'on pourrait retenir une option, sans avoir ouvert l'espace d'entendre la position des collègues, puisqu'ils pourront exprimer une tension a posériori et hop... Peux-tu clarifier ton intention en ajoutant cet élément là?
Une proposition "les émotions", et pas "l'émotion".

**Comment by DavidDrayer** [comment]
Pour moi, la définition qui est donnée ici peut amener à un dysfonctionnement que je constate régulièrement: l'absence de proposition souveraine.
Il n'est pas rare que les personnes amènent des questions plutôt que des propositions: "Que pensez-vous du fait de faire ci ou faire ça", dans le but d'entendre ses collègues, alors que leur avis est déjà orienté.
S'ensuit un débat difficile, et qu'il est difficile de cadrer.
Dans notre pratique, nous encourageons à venir avec une proposition affirmée et claire, tout en se laissant l'espace du lien qui consiste à faire de son mieux pour intégrer les besoins des autres, et surtout à se permettre de bonifier la proposition en gardant une posture flexible. Le lien est en fait la matérialisation de ma posture lorsque je reçois les propositions des autres, que je ne perçois pas comme des jugements et des attaques, mais comme des contributions.

**Comment by jeanlucchristin** [comment]
@Maylis-De-Almeida effectivement le avant/après crée de la confusion, je vais le retravailler. 

@DavidDrayer , pour bien te comprendre, peux tu préciser si tu penses la même chose d'une sollicitation d'avis ou s'il y a une différence ?

**Comment by DavidDrayer** [comment]
@jeanlucchristin, J'invite en tout cas chacun-e a être conscient de ce qui est déjà présent en lui/elle et à l'exprimer: Si je fais une sollicitation d'avis sans aucune préférence, alors c'est ok de demander "Où est-ce que vous voulez aller manger ?".
Mais si je sais que logistiquement il est plus facile d'aller à l'italien du coin ou à l'asiatique de la gare, autant rentrer ça tout de suite dans la demande.
Et si moi personnellement je préfère aller à l'Italien, autant également le rendre visible: "Je dois organiser le souper de fin d'année, j'ai une préférence pour l'italien du coin. Il y aurait une autre option facile à organiser avec l'asiatique de la gare, et je veux bien votre avis: Est-ce que cela vous conviendrait ou avez-vous d'autres besoins ou idées ?"

Si je ne suis pas clair là dessus, je risque de devoir faire passer les besoins des autres avant les miens, ou générer cette impression que je n'ai pas écouté les avis puisque j'ai finalement décidé autre chose, ce qui était en moi avant mais que je n'avais pas exprimé.

**Comment by jeanlucchristin** [comment]
Voici une nouvelle version tenant compte de vos feedbacks. 

Merci de vos avis 

![image](https://user-images.githubusercontent.com/38285180/234050099-32a0e52b-f5bd-4d63-80fa-291115389c2b.png)

**Comment by christophe-herault** [comment]
Cette version me parait beaucoup plus claire. Mais je ne suis pas d'accord avec la formulation "L'inconvénient est (...) la perte de souveraineté chez celles et ceux qui voudraient se laisser influencer". En effet, je peux tout à fait être souverain et me laisser influencer, si c'est mon choix conscient et libre de me laisser influencer, car je veux intégrer l'avis des autres. Il me semble que ce à quoi tu veux faire référence n'est pas un inconvénient inhérent au lien. Il me semble que tu fait référence au risque de suradaptation, qui consisterait à renoncer à ce qui est bon pour soi par peur de déplaire.

**Comment by jeanlucchristin** [comment]
souveraineté et lien

**Comment by jeanlucchristin** [comment]
Bien reçu, voici une version qui tient compte de cette finesse. 

![image](https://github.com/jeanlucchristin/constitution-cellular-governance/assets/38285180/c83a13c4-5e5f-4519-8561-1eaecd737519)

**Comment by christophe-herault** [comment]
merci pour la modif. Je crois que je préfère encore supprimer le bout de phrase "et le risque pour certain de renoncer à ce qui leur semble pertinent par peur de déplaire", car cela n'est pas inhérent au lien seul.
En fait, je pense que cela a sa place dans le paragraphe d'après qui parle de l'équilibre entre les deux. On pourrait y placer une phrase comme celle ci tout à la fin (pour illustrer la notion d'équilibre) : "Il s'agira de trouver le moyen de ne pas renoncer à sa souveraineté au nom du lien (par exemple : se suradapter par crainte de déplaire), ni à sacrifier le lien au nom de sa souveraineté."

**Comment by jeanlucchristin** [comment]
@christophe-herault 

Merci pour ces contributions. 
Dans ma représentation, le risque de trop privilégier le lien est bien une perte de souveraineté. 
D'un point de vue psychologique, je comprends que tu considères, à l'instar de Will Schutz et de l'élément humain, que les personnes qui perdent leur souveraineté le choisissent. 
Mais la constitution ne s'adresse pas aujourd'hui à des gens à ce niveau de compréhension ni d'autonomie. 

Mon choix sera donc d'alerter les personnes qui lisent la constitution sur le risque de perdre sa souveraineté au bénéfice de préserver le lien. 

@DavidDrayer @Maylis-De-Almeida @Bonzepiss un avis ?

**Comment by Maylis-De-Almeida** [comment]
Coucou, je pense qu'il est utile d'alerter les personnes sur le risque que tu nommes Jeanluc. Dans mon exp de vivre la GC, avec des gens qui ne sont pas du tout coachs, accompagnants, etc... c'est un sacré enjeu (d'ailleurs, même avec des gens qui le sont, dans Buurtzog par exemple). 
J'aime bien la formulation proposée par Christophe, qui nomme clairement ce que revêt "l'équilibre subtil"
Mon avis à ce stade serait:
- dans le paragraphe lien, la formulation "et le risque pour certain de renoncer à ce qui leur semble pertinent par peur d'abimer la relation."
- dans le dernier paragraphe, la formulation proposée par Christophe.

Mon inquiétude est que ça fasse un peu bcp, mais au moins ça pose le truc!

**Comment by jeanlucchristin** [comment]
Quelque chose qui ressemblerait à cela ? 

J'ai l'impression qu'on se répéte et que cela alourdit, mais si cela vous parait plus clair, pourquoi pas. 
![image](https://github.com/jeanlucchristin/constitution-cellular-governance/assets/38285180/bd8f61ba-f428-4f06-ad9f-43726c0bfd76)

**Comment by Maylis-De-Almeida** [comment]
Yep, un peu lourd en effet. Et assez clair à mes yeux. J'ai pas de vision des rôles et redevabilité dans cet espace, ma proposition ici serait que tu décides de ce qui te semble juste et clair après tous ces avis et précisions ; )

**Comment by jeanlucchristin** [comment]
En relisant après quelques mois, je trouve que la formulation du dernier paragraphe est effectivement lourde, mais surtout presque incompréhensible. 

Je l'ai allégée, voici la version actuelle. 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/cfde3dfa-f361-4e79-93e4-15848e533f6c)


Je crois que la version est suffisamment aboutie, je clos l'issue et nous la réouvrirons si besoin.
