### ISSUE TITLE
raison d'etre gouvernance cellulaire 

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/La_demarche_gouvernance_cellulaire#105]
Proposition d'évolution de la raison d'être de gouvernance cellulaire : 

**Offrir une démarche pour créer sa propre gouvernance, avec une constitution repère et une boite à outils complémentaires, car nous considérons les professionnels capables de construire leur propre organisation saine et performante par ajustements successifs.**

**Comment by jeanlucchristin** [comment]
### raison d'etre gouvernance cellulaire

**Contribution au monde :** 
Offrir une démarche pour créer sa propre gouvernance, avec une constitution repère et une boite à outils complémentaires, car nous considérons les professionnels capables de construire leur propre organisation saine et performante par ajustements successifs.
**Pour nos contributeurs :** 
Donner forme à un rêve en l'expérimentant pour faire notre part vers un monde où action rime avec altruisme
**Pour nos investisseurs :** 
Nous n'avons pas d'investisseur.

**Comment by DavidDrayer** [comment]
Il y a un truc qui me dérange profondément, c'est cette différence entre contributeurs et investisseurs... personnellement, comme contributeurs, j'ai investi des heures et des heures dans ce projet... donc quand je vois "nous n'avons pas d'investisseurs", ça me chagrine et ça me rappelle que l'investissement continue d'être vu dans le spectre très étroit de l'argent.
Bref, cette formulation, en ouverture du document, aurait plutôt tendance à me bloquer. Pourquoi ne pas intégrer la notion de parties prenantes, plus souple que de limiter au monde/contributeurs/investisseurs ?

**Comment by jeanlucchristin** [comment]
### raison d'etre gouvernance cellulaire

**Contribution au monde :**
Offrir une démarche pour créer sa propre gouvernance, avec une constitution repère et une boite à outils complémentaires, car nous considérons les professionnels capables de construire leur propre organisation saine et performante par ajustements successifs.
**Pour nos contributeurs :**
Donner forme à notre rêve d'un monde de coopération efficace et humaniste. 
**Pour nos investisseurs :**
Nous n'avons pas d'investisseur financier en attente de contre-partie.

**Comment by christophe-herault** [comment]
Je suis tout à fait OK avec cette version que nous avons discuté et ajusté ensemble !

**Comment by Nicobe73** [comment]
OK pour moi (je commence à accepter le terme investisseur...)

**Comment by jeanlucchristin** [comment]
![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/b91a7a7d-0b4f-470a-be24-616b7547f720)

Je clos cette issue avec ce résultat suffisamment satisfaisant, nous la réouvrirons si besoin.
