### ISSUE TITLE
Changement du nom du document

### ISSUE THREAD

**Issue by DavidDrayer** [jeanlucchristin/La_demarche_gouvernance_cellulaire#106]
Le document nommé "Constitution Gouvernance Cellulaire" contient aujourd'hui plus qu'une constitution: les aspects philosophiques, les outils et autres concepts n'appartiennent pas à une constitution.
Dans le cadre du projet de réorganisation du document, ce phénomène est d'autant plus visible qu'un cahier "constitution repère" est clairement identifié dans le document.
Dans ce sens, il est proposé de définir le nom du document afin que le même vocabulaire soit utilisé par tous et toutes.

**Un jugement majoritaire a été créé pour collecter les différentes propositions d'ici au 20 juillet: [https://jm.instantz.org/s/2014](https://jm.instantz.org/s/2014)**

Des propositions peuvent être faites jusqu'au 20 juillet, puis débutera une période de positionnement jusqu'au 20 août.

**Comment by jeanlucchristin** [comment]
Version Actuelle : 

![image](https://github.com/jeanlucchristin/constitution-cellular-governance/assets/38285180/47c2122f-6fc0-4224-a145-e7c00cd4c6dc)

Version en émergence : 

![image](https://github.com/jeanlucchristin/constitution-cellular-governance/assets/38285180/7c11c435-1fd8-4cc9-b6ca-421a26abb2d3)

**Comment by jeanlucchristin** [comment]
L'équipe gouvernance cellulaire était frileuse sur le terme "aventure", le nouveau nom sera "la démarche gouvernance cellulaire".
