### ISSUE TITLE
Envisager une diapo "Régulation"

### ISSUE THREAD

**Issue by JCC45** [jeanlucchristin/La_demarche_gouvernance_cellulaire#108]
Avoir une diapo "esprit" de la régulation indépendante de la méthode et avoir CNV et Marcher-Parler dans les outils

**Comment by DavidDrayer** [comment]
Je plussoie!

**Comment by jeanlucchristin** [comment]
Il y a cela qui s'annonce. 

Je ne sais pas si ça répond à l'attente. 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/43e628bb-90eb-4deb-8bb3-02943ee00725)

**Comment by jeanlucchristin** [comment]
Le marcher parler a fait son entrée dans la constitution repère
la régulation CNV est passée en mode optionnelle (trop difficile à animer par rapport au marcher parler)
la rétrospective relationnelle fait sa grande entrée dans la version 2024.
