### ISSUE TITLE
Adoption et modification de la constitution

### ISSUE THREAD

**Issue by christophe-herault** [jeanlucchristin/La_demarche_gouvernance_cellulaire#109]
Je propose d'ajouter à la constitution repère les deux slides ci-jointes qui définissent comment la constitution est adoptée et comment elle est modifiée.
Je propose que ce soit dans la constitution repère car ça me semble des éléments indispensables à toute constitution.
[constit adoption.pdf](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/files/12706874/constit.adoption.pdf)

**Comment by jeanlucchristin** [comment]
La proposition du slide sur la modification de la constitution me parait apporter quelque chose de nouveau, je suis assez fan de la travailler. 
Des avis ? 
![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/a4ebd0f1-42a9-475b-b115-872c6b6a85eb)

**Comment by Nicobe73** [comment]
Je suis aussi de cet avis (Christophe nous l'a proposé lors du seminaire de l'équipe GC)

**Comment by jeanlucchristin** [comment]
Par contre, l'adoption me semble faire double emploi avec le "contrat de liberté d'agir". Il y a deux conversations mélangées.  
@christophe-herault serais tu ok pour sortir ce second sujet de l'issue 109 en en créant une nouvelle issue dans laquelle ta proposition serait copiée collée ?

**Comment by jeanlucchristin** [comment]
Bonjour, voici une proposition sur la base de votre proposition. 

La définition serait également copiée dans le glossaire. 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/1ea5b481-695a-4300-b390-b049b7e2e76d)

**Comment by jeanlucchristin** [comment]
Pour ne pas faire double emploi avec le contrat de liberté d'agir, je pars sur ces deux slides. 

Des aveis négatifs sur cette proposition ? 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/e8b527c8-7be3-40b7-8f78-4e755645c9ed)


![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/9393170c-4dee-4a18-858b-b3936623a9a1)

**Comment by Nicobe73** [comment]
Pour moi, c'est clair et en lien avec les questions que l'on se pose en écrivant la constitution de l'équipe GC. 
Une question sur le fait de "signer". Je me dis que si lors d'une réunion la constitition est présentée et qu'il y a consentement voir concordance des participants, un PV de la réunion peut avoir le même pouvoir que de signer.

**Comment by jeanlucchristin** [comment]
@Nicobe73 pour la signature ou non, je rajoute une phrase en début de slide : 

"*Comme tout document de la démarche gouvernance cellulaire, celui ci peut être modifié*"

Je crois que c'est effectivement une bonne idée de rappeler que chacun·e est libre d'ajuster tous les processus.

**Comment by jeanlucchristin** [comment]
Et je clos l'issue, nous sommes arrivé à quelque chose de suffisamment satisfaisant. 
Si quelqu'un a besoin nous la ré-ouvrirons.

**Comment by jeanlucchristin** [comment]
Et je clos l'issue, nous sommes arrivé à quelque chose de suffisamment satisfaisant.
Si quelqu'un a besoin nous la ré-ouvrirons.

**Comment by Bonzepiss** [comment]
Hello, où se trouve la dernière version à jour de la constitution? je ne la trouve pas sur github. thx

**Comment by jeanlucchristin** [comment]
@Bonzepiss La derniere version est ici : 
https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/releases/tag/V3.2

La future version est en fin d'élaboration, elle sortira dans 3 ou 4 mois. 
Dernière version dispo en slides sur gouvernancecellulaire.org

**Comment by Bonzepiss** [comment]
OK et merci Jean-Luc! je pensais commencer la version anglaise et partir de la dernière mouture ;)

**Comment by jeanlucchristin** [comment]
Ah génial,

Attend un peu, je suis sur l'avant projet.

D'ici peu il sera assez avancé, je te dis ?
Ou tu avais du temps juste maintenant ?

Jean-Luc Christin

0675518156
*https://gouvernancecellulaire.org/ <https://gouvernancecellulaire.org/>*

Je crois que si chacun prend le temps d'écouter le sage murmure de la vie
au fond de soi, nous construirons un monde dans lequel j'ai envie de vivre.
Je m'efforce de participer à cela.

**Comment by Bonzepiss** [comment]
Ok cool ça marche
Bien à toi


Le mer. 25 oct. 2023, 14:56, Jeanluc Christin ***@***.***> a
écrit :

> Ah génial,
>
> Attend un peu, je suis sur l'avant projet.
>
> D'ici peu il sera assez avancé, je te dis ?
> Ou tu avais du temps juste maintenant ?
>
> Jean-Luc Christin
>
> 0675518156
> *https://gouvernancecellulaire.org/ <https://gouvernancecellulaire.org/>*
>
> Je crois que si chacun prend le temps d'écouter le sage murmure de la vie
> au fond de soi, nous construirons un monde dans lequel j'ai envie de
> vivre.
> Je m'efforce de participer à cela.
>
>
