### ISSUE TITLE
Slide rétrospective à dédoubler

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/La_demarche_gouvernance_cellulaire#110]
A l'usage, le slide rétrospective est difficile à animer. 
Le mélange de l'espace lien (célébration relationnelle) avec l'espace contrat (célébration collective) ou l'espace sens (décision de la stratégie) est difficile à suivre pour les participants. 

La proposition est ci dessous, avec un élément **_rétrospective et ambition_** et un élément **_ajustements relationnels_**. 

Je veux bien vos réactions, idées, etc. 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/11dcf269-3c2f-4478-96de-507de772fd34)

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/77fb74be-1344-47b3-bb53-9849e09f8a8c)

**Comment by DavidDrayer** [comment]
Dans la plupart des organisations, il y a besoin de séparer la partie bilan opérationnel du bilan relationnel. J'aime bien l'idée d'avoir séparé les deux.

**Comment by christophe-herault** [comment]
Retour de la cellule laboratoire de l'équipe Gouvernance Cellulaire : 
- David Drayer : le nom "ajustement relationnel" n'est pas très joyeux et porteur.
- Georges Comby : propose d'utiliser le nom de "rétrospective relationnelle". Propose que le chapitre "processus" soit renommé en "processus proposé". 
- Jean-Christophe Cicéron : je partage les points précédents. Je recommande aussi de modifier la dernière phrase "temps difficile à vivre"
- Christophe Hérault:  très pertinent de séparer les deux temps. Je recommande le temps sur la relation soit rattaché à l'espace Lien.

**Comment by jeanlucchristin** [comment]
Merci pour vos retours. Tentons rétrospective relationnelle. Voici ce que cela donne. 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/1a8c6559-afe6-477b-bdd6-1941b3cabc1f)
