### ISSUE TITLE
efficacité humaniste et autodiagnostic

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/La_demarche_gouvernance_cellulaire#111]
Bonjour

Ce slide est en révision majeure pour le rendre plus facile d'usage. 

Retours bienvenus.

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/a0f069ad-9381-4f11-9dcc-525a646e0800)

**Comment by JCC45** [comment]
SalutC'est un test car je ne vois que (voir pièce jointe) : le plus efficace....Une clarification...Amicalement JC Le 02/02/2024, 13:47 Jeanluc Christin ***@***.***> a écrit:

   
  Bonjour 
  Ce slide est en révision majeure pour le rendre plus facile d'usage. 
  Retours bienvenus. 
  image.png (view on web)

**Comment by jeanlucchristin** [comment]
@JCC45 merci, c'était une erreur, j'ai corrigé.

**Comment by DavidDrayer** [comment]
J'aime bien la structure, qui défini l'efficacité-humaniste, et propose de s'autodiagnostiquer. Cependant, la notion d'autodiagnostique uniquement basé sur "on se pose la question" me semble un peu légère... je trouverais intéressant de proposer quelques exemples de questions sur les 3 espaces.

**Comment by christophe-herault** [comment]
Retours de la Cellule Labo : 
- Jean-Christophe Cicéron : Ca me plait d'expérimenter cette version
- Georges : cette version de slide est beaucoup plus claire. Pour l'autodiag, je partirais des rituels de l'équipe pour faire le constat de ce qu'on a déjà dans chaque espace lien, contrat et sens pour l'aider dans un 2è temps à choisir là où elle a le plus à gagner.
- Christophe Hérault : cette version est beaucoup plus claire. La dimension autodiag de cette slide est décrite trop succintement pour que des novice s'en emparent. Elle mériterait d'être développper dans une slide à part comme un outil.

**Comment by jeanlucchristin** [comment]
Ok merci des retours. On va en rester là pour le moment, on attendra d'avoir des retours d'expérience. 
Moi qui m'en sers ainsi depuis des années, j'ai vu que les équipes sont très à l'aise pour nommer dans quel espace elles veulent travailler. 
Si un slide détaillé propose des questions plus tard, ce sera pour investiguer à l'intérieur d'un espace.
