### ISSUE TITLE
Slides valeurs

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/La_demarche_gouvernance_cellulaire#112]
Nouveauté en préparation pour la version 2024 : 2 slides sur les valeurs. 

Avis bienvenus 

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/b21d36e2-17c9-41fa-8789-1159cd99aa15)

![image](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/assets/38285180/5000f7be-cdd3-4a8c-870b-80b45bf535b5)

**Comment by DavidDrayer** [comment]
super processus, je vais l'intégrer dans mes pratiques.
Points de détail: peut-être trop précis, dans le sens où les notions de timing et de taille de groupes, tellement variables selon le contexte et la culture des orga. 
Une phrase qui me dérange à plusieurs endroits, c'est "Ce processus peut-être difficile à vivre"... quelle est l'utilité de cette mise en garde?

**Comment by christophe-herault** [comment]
Retour de Jean-Christophe Cicéron : J'ai le sentiment qu'il il y a une intention utile à la matrice. En revanche, l'exemple de processus semble assez contraignante, et peut-être devrait être présentée comme optionnelle.  La dernière phrase 'ce processus peut-être difficile à vivre' devrait plutôt être écrite de manière positive.

**Comment by christophe-herault** [comment]
J'aime beaucoup l'ensemble de la proposition
Je propose de supprimer la touche d'humour "sur l'air de Téléphone" parce que ça induit de la confusion.
Je recommande aussi de trouver une autre formulation  que le "temps difficile à vivre"

**Comment by GeorgesComby** [comment]
j'aime beaucoup la matrice avec les 4 quadrants
je trouve l'exemple de processus trop "rigide"
quand à la phrase "peut être difficile à vivre", si tu crois que ça va être difficile, ca le sera => je resterai avec l'importance d'une clôture pour questionner l'efficacité" (et si besoin noter les tensions (traiter plus tard) et l'humanisme
