### ISSUE TITLE
Chapitrage de la constitution

### ISSUE THREAD

**Issue by DavidDrayer** [jeanlucchristin/La_demarche_gouvernance_cellulaire#93]
Aller hop, un pavé dans la mare :)

Suite à la dernière formation en GC, il ressort que beaucoup des concepts de la GC intéressent surtout les coachs et les explorateurs de la GP, et non pas les utilisateurs de base. 
A mon avis, le chapitre 3 "élément coeur" mélange trop les choses: il y a des concepts, des éléments philosophiques, des processus de réunion et des modes de prise de décision, entièrement mélangés. C'est innaviguable de mon point de vue, encore plus dans la version texte qui ne bénéficie pas de la navigation par click.

Il y a un chapitre 4 nommé rôles préconstruits... et je propose de garder cette logique:

- Chapitres 1 et 2 : Philosophie et intention de la GC
- Chapitre 3 : Concepts de base de la GC (3 espaces, culture essai-erreur, principe de souveraineté, pilotage par la raison d'être, circuit des demandes...)
- Chapitre 4 : Outils  (auto-diagnostique efficacité humaniste, curseur managérial, niveaux de délégation)
- Chapitre 5 : Rôles structurels préconstruits (lead, représentation, facilitation, mémoire, protection, bonté, source,...) + comment construire un rôle
- Chapitre 6 : Temps (ou réunions) préconstruits : opérations, réorg, pilotage de soi, positionnement éthique,...) + comment construire sa propre réunion
- Chapitre 7 : Éléments optionnels : pour aller plus loin, classé de la même manière
> - Concepts optionnels (3 piliers éthiques, estime de soi,...)
> - Outils optionnels (OMO, Trello, ...)
> - Rôles optionnels (ami impitoyable,...)
> - Temps (ou réunions) optionnels (régulation, débloquage 180°,...)

**Comment by christophe-herault** [comment]
@DavidDrayer 
Je partage aussi ce constat que différents niveaux logiques sont mélangés (philo, principes, processus, etc) et que ça rend le doc difficile à utiliser. Je vote aussi pour la structuration de la constitution en chapitres.
Par exemple, j'accompagne une entreprise dans sa transfo en GC, et j'ai regroupé les éléments que je leur ai transmis en chapitres. 

Ma proposition reprends celle de David pour en proposer quelques variantes en gras :
- Ch 1 & 2 : Philosophie et intention
- Ch 3: les **principes fondateurs** de la GC : 3 espaces, culture essai-erreur, principe de souveraineté, pilotage par la raison d'être, circuit des demandes, **responsabilité de structure, responsabilité de membre.**  J'y ajouterais aussi 2 autre principes que je ne vois pas dans la constitution (je vais faire un prop à part sur Git Hub) : Primauté de la constitution, et Principe de transparence.
- Ch 4 : **Outils structurels** : auto-diagnostic efficacité humaniste, curseur managérial, niveaux de délégation
- Ch 5 : **Principes de structuration** : **L'organisation en cellules et rôles,** les rôles préconstruits, comment construire un rôle
- Ch 6 : Les **Processus** de l'espace Contrat (le temps opérations, temps réorg, etc)
- Ch 7 : Les **processus** de l'espace Relation 
- Ch 8 : Les **processus** de l'espace Sens
- Ch 9 : Éléments optionnels : pour aller plus loin, classé de la même manière
        Concepts optionnels (3 piliers éthiques, estime de soi,...)
        Outils optionnels (OMO, Trello, ...)
        Rôles optionnels (ami impitoyable,...)
        **Processus** optionnels (régulation, débloquage 180°,...)

**Comment by jeanlucchristin** [comment]
Pas facile ce sujet. 

Soit on considère la gouvernance cellulaire comme un bloc et votre approche est logique. (philosophie, principes, outils...)
Soit on garde la logique d'éléments autonomes et indépendant et c'est plus délicat. Chaque élément a besoin de sa cohérence avec philosophie etc. 

Ceci dit, pour la version 2022, nous en avons tenu compte pour les éléments coeurs et nous sommes en train d'essayer de préparer les éléments optionnels en repérant la philo et les outils. 

Voici ce à quoi nous arrivons

**Comment by jeanlucchristin** [comment]
Element optionnels option 1 
![image](https://user-images.githubusercontent.com/38285180/148782316-9099e071-a3eb-4653-9817-f79c2979d7e3.png)

**Comment by jeanlucchristin** [comment]
Eléments optionnels avec philo et outils 
![image](https://user-images.githubusercontent.com/38285180/148782480-eb13cd76-bc7e-4d34-8290-b913af24d3d0.png)

**Comment by jeanlucchristin** [comment]
Hello, 

On a avancé sur les éléments pour les classer en "philosophie" et "structuration". 

Ca donne cela. 

![image](https://user-images.githubusercontent.com/38285180/157896409-d16cdde2-ef66-4bc6-b39c-57e2a9f2e82d.png)

**Comment by jeanlucchristin** [comment]
Hello, 

Je tente une dernière compréhension et mise en oeuvre de vos propositions. 

Il me semble 

- qu'on perd la notion d'éléments coeurs. (mélange entre éléments coeurs et éléments optionnels).
- que le lien est à réinjecter.

Voici à quoi cela ressemble dans ce que je comprends : 

![image](https://user-images.githubusercontent.com/38285180/158056474-691b7171-ffb6-4e2b-9d9c-9a1f30db1316.png)

Pour info, voici à quoi ressembleront les éléments coeurs dans la version 2022 : 

![image](https://user-images.githubusercontent.com/38285180/158056520-8da51b49-863d-4941-b17d-dcd6f58e802e.png)



Q

**Comment by jeanlucchristin** [comment]
Nous relançons le sujet du chapitrage de la constitution avec celles et ceux qui étaient impliqué·es. 

Voici le plan d'action : 

Intention : 
Créer un chapitrage de la gouvernance cellulaire qui permette une lecture de type universitaire, avec une logique d'introduction puis de déroulé logique, avec une table des matières dédiée. 
Ce chapitrage viendra se juxtaposer à l'arborescence des slides. Cette arborescence sera la clef d'entrée pour une lecture au click. Le chapitrage rendra par exemple une lecture claire à une personne qui imprimerait le document. 

Décisions : 

- Nous séparerons les slides comportant un élément réglementaire des slides qui n'en comportent pas. Action en toutes libertés : @DavidDrayer. 
- Nous repèrerons les slides d'introduction existants avant soit de le ou les modifier soit d'en créer un pour qu'il introduise le chapitrage. Action en toutes libertés : @christophe-herault  et Nicolas Begel
- CR de la réunion (rédaction et publication ghitub) : @jeanlucchristin 

Prochaine réunion : 21 avril 16h30
Actions futures non encore affectées : 
Essayer de modifier les titres de paragraphes de slides pour aller vers "Intention, Création, et Règle/processus.
Remplacer le terme "processus" du slide autodiagnostic par "Fonctionnement" pour lever l'ambiguïté entre cette utilisation du terme processus et celle d'une règle sur la façon de faire (comme le processus de triage par exemple).

**Comment by GeorgesComby** [comment]
chouette, de se lancer sur un chapitrage.
l'indexation de l'information est aussi importante que l'information elle-même

**Comment by jeanlucchristin** [comment]
Plan d'action suite à la réunion ouverte du 21 avril 2023 :

Intention :
Créer un chapitrage de la gouvernance cellulaire qui permette une lecture de type universitaire, avec une logique d'introduction puis de déroulé logique, avec une table des matières dédiée.
Ce chapitrage viendra se juxtaposer à l'arborescence des slides. Cette arborescence sera la clef d'entrée pour une lecture au click. Le chapitrage rendra par exemple une lecture claire à une personne qui imprimerait le document.

TENSIONS : 

**- cible :** 
La constitution est rédigée pour être utilisable prioritairement par des acteurs internes ou externes de la transformation des organisations.

**- raison d'être :** 
L'oeuvre GC fourni une constitution repère à partir de laquelle les équipes peuvent créer la leur en utilisant tout ou partie des éléments proposés ou leurs propres éléments. 

 **- proposition de chapitrage :** 
INTRO 
   - Préface histoire (de untel·le et/ou story telling  et/ou le mot du rôle source.
   - Que permet de faire ce document ? (raison d'être, cible)
   - Qu'est ce qu'une constitution ? 
   - Comment est structuré ce document et comment l'utiliser ?
  
CONTENU
  - Partie philo de la GC, (les slides à connotation philosophique non constitutionnels)  
  - Constitution repère (avec tous les éléments qui la composent, peut-être en changer certains)
  
  - éléments optionnels chapitrés (rôles structurels, processus de réunion... )
  - éléments complémentaires liés à la posture et aux bonnes pratiques



Actions en cours ou à lancer : 

- Lancer un issue sur le terme constitution @christophe-herault 
- proposer de sortir le role prendre soin de la constitution repère (@jeanlucchristin 
- proposer de Re-écrire le role prendre soin @GeorgesComby 
- proposer de re-organiser le slide Raison d'être de la gc @christophe-herault 
- proposer de re écrire les roles structurels @DavidDrayer 
- intégrer les roles structurels dans l'arborescence @jeanlucchristin 

Finir de séparer les slides comportant un élément réglementaire des slides qui n'en comportent pas. Action en toutes libertés : @DavidDrayer.
Nous repèrerons les slides d'introduction existants avant soit de le ou les modifier soit d'en créer un pour qu'il introduise le chapitrage. Action en toutes libertés : @christophe-herault et Nicolas Begel

Prochaine réunion : 24 mai 08h30 à 10h
https://us02web.zoom.us/j/7445925482

Actions futures non encore affectées
- Essayer de modifier les titres de paragraphes de slides pour aller vers "Intention, Création, et Règle/processus.
- fresque @GeorgesComby

**Comment by jeanlucchristin** [comment]
Actions décidées : 
-  @christophe-herault et Nicolas mettent en forme de slide leur proposition d'intro
-  @GeorgesComby propose le role prendre soin sous github
-  @DavidDrayer crée un espace pour proposer des noms et @DavidDrayer crée un jugement majoritaire autour du nom 
-  @jeanlucchristin crée une issue raison d'être

**Comment by christophe-herault** [comment]
Résultat de l'action "@christophe-herault et Nicolas mettent en forme de slide leur proposition d'intro" : 
Nicolas, Jeanluc et Christophe se sont réunis et on aboutit à cette proposition pour restructurer l'intro du document : 
https://workdrive.zohopublic.eu/external/d4871fcb6c1d84c58aeed338da6ddb464fa7c30c2e589a4fa05f01c60b8b82cf 
Remarque : il s'agit d'une maquette. La mise en forme des textes (font, alignement, etc) n'est pas encore travaillée.

Merci de partager vos réactions et avis sur cette proposition !

**Comment by jeanlucchristin** [comment]
Relevé de décisions réunion du 29 aout 2023
Le chapitrage est validé tel que présenté dans le document en supprimant les notions de section et de sous sections. 
Le nom du futur document devient la démarche gouvernance cellulaire  

précédentes actions 
• proposer de Re-écrire le role prendre soin [@GeorgesComby](https://github.com/GeorgesComby)
• proposer de re-organiser le slide Raison d'être de la gc [@christophe-herault](https://github.com/christophe-herault)
• proposer de re écrire les roles structurels [@DavidDrayer](https://github.com/DavidDrayer)
• intégrer les roles structurels dans l'arborescence [@jeanlucchristin](https://github.com/jeanlucchristin)
• Finir de séparer les slides comportant un élément réglementaire des slides qui n'en comportent pas. Action en toutes libertés : [@DavidDrayer](https://github.com/DavidDrayer).

Actions futures non encore affectées
• Essayer de modifier les titres de paragraphes de slides pour aller vers "Intention, Création, et Règle/processus.
• fresque [@GeorgesComby](https://github.com/GeorgesComby)

**Comment by christophe-herault** [comment]
Voici le résultat du travail collectif (Georges, Jean-Christophe, Nicolas, Christophe, Jeanluc et David) : une proposition de chapitrage du document de la démarche GC. Commentaires et réactions bienvenus !
[Démarche GC (prop chapitrage) V1.pdf](https://github.com/jeanlucchristin/La_demarche_gouvernance_cellulaire/files/12703016/Demarche.GC.prop.chapitrage.V1.pdf)

**Comment by jeanlucchristin** [comment]
Le travail de chapitrage est terminé, je clos cette issue
