### ISSUE TITLE
Alternatives au lexique de la gouvernance cellulaire pour les organisations

### ISSUE THREAD

**Issue by MarvinChambe** [jeanlucchristin/La_demarche_gouvernance_cellulaire#95]
Salut ! 

Dans le cadre de la cellule "Guide de l'accompagnement" (un rejeton de la cellule écriture), David, Nicolas et moi travaillons à la finalisation d'un document destiné spécifiquement aux accompagnants à la transfo des organisations. Nous avons eu l'idée d'envisager d'un "tableau de correspondance / conversion" de certains éléments de vocabulaire pour faciliter l'appropriation de la gouvernance cellulaire dans des organisations aux cultures variées, et limiter les blocages de forme. exemple : "cellule" peut-être remplacé par "équipe".
Avez-vous des retours d'expérience à nous partager sur le sujet ? Le cas échéant, n'hésitez-pas à compléter ce lien :
[ici](https://docs.google.com/document/d/1qVeRdbZFWiuCPlhJndFaakj8ITa1FdvFAfJdZyRWcMk/edit)

Merci à vous :)

**Comment by christophe-herault** [comment]
J'ai complété le lexique avec des expressions que je rencontre habituellement.
C'est chouette d'avoir ce document !

**Comment by jeanlucchristin** [comment]
Top document de travail mais il ne propose pas une évolution de la démarche gouvernance cellulaire, 
du coup je clos cette issue. Nous la réouvrirons si besoin.
